name: Increment and Update k510 Counter

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch and increment counter from Upstash
        id: get_and_inc
        run: |
          # Fetch the current value
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.UPSTASH_TOKEN }}" \
            "${{ secrets.UPSTASH_URL }}/get/k510-global-counter")
          value=$(echo "$response" | jq -r '.result')
          if [[ "$value" == "null" || -z "$value" ]]; then value=0; fi

          # Increment
          new_value=$(( value + 5 ))

          # Store new value
          curl -s -X POST -H "Authorization: Bearer ${{ secrets.UPSTASH_TOKEN }}" \
            "${{ secrets.UPSTASH_URL }}/set/k510-global-counter/$new_value"
          echo "new_counter=$new_value" >> $GITHUB_ENV

      - name: Generate static HTML
        run: |
          cat > k510-static.html <<EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <title>510(k) Mappings Static Counter</title>
            <style>
              body { font-family: Arial, sans-serif; padding: 40px; text-align: center; }
              .counter-value { font-size: 2.5em; margin: 20px 0; }
            </style>
          </head>
          <body>
            <h1>510(k) Mappings (Static Counter)</h1>
            <div class="counter-value">${{ env.new_counter }}</div>
            <p>Last updated: $(date -u)</p>
          </body>
          </html>
          EOF

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k510-static.html
          git diff --cached --quiet || git commit -m "Update k510-static.html [skip ci]"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git pull --rebase origin main
          git push origin HEAD:${GITHUB_REF#refs/heads/}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
