name: Increment and Update Drug Application Counter

on:
  workflow_dispatch:

jobs:
  update-text:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch and increment Drug counter from Upstash
        id: get_and_inc
        run: |
          echo "UPSTASH_URL: ${{ secrets.UPSTASH_URL }}"
          echo "UPSTASH_TOKEN: ${#${{ secrets.UPSTASH_TOKEN }}} chars"

          # Fetch the current value
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.UPSTASH_TOKEN }}" \
            "${{ secrets.UPSTASH_URL }}/get/drug-global-counter")
          echo "Upstash response: $response"
          value=$(echo "$response" | jq -r '.result')
          if [[ "$value" == "null" || -z "$value" ]]; then value=0; fi
          echo "Current counter: $value"

          # Increment
          new_value=$(( value + 5 ))
          echo "Incremented counter: $new_value"

          # Store new value
          curl -s -X POST -H "Authorization: Bearer ${{ secrets.UPSTASH_TOKEN }}" \
            "${{ secrets.UPSTASH_URL }}/set/drug-global-counter/$new_value"
          echo "new_counter=$new_value" >> $GITHUB_ENV

      - name: Generate plain text file with just the value
        run: |
          echo -n "${{ env.new_counter }}" > drug-counter.txt

      - name: Commit and robust push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add drug-counter.txt
          git diff --cached --quiet || git commit -m "Update drug-counter.txt [skip ci]"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

          n=0
          until [ $n -ge 5 ]
          do
            git pull --rebase origin main || true
            if git push origin HEAD:${GITHUB_REF#refs/heads/}; then
              echo "Push succeeded!"
              break
            else
              echo "Push failed, retrying in 10 seconds..."
              n=$((n+1))
              sleep 10
            fi
          done

          if [ $n -eq 5 ]; then
            echo "Push failed after 5 attempts"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
